basePath: api
consumes:
- application/json
definitions:
  PushOrdinalValuesPayload:
    properties:
      ordinal:
        description: The ordinal position within the stream
        format: int64
        type: integer
      stream:
        description: Identifies the stream that the ordinal value relates to
        type: string
      value:
        description: The value at the ordinal position
        format: double
        type: number
    required:
    - stream
    - ordinal
    - value
    title: PushOrdinalValuesPayload
    type: object
  RegisterOrdinalValuesPayload:
    properties:
      intervalSize:
        description: The ordinal position within the stream
        format: int64
        type: integer
      maxIntervalLag:
        description: The value at the ordinal position
        format: int64
        type: integer
      stream:
        description: Identifies the stream that the definition relates to
        type: string
      targetSampleSize:
        description: The value at the ordinal position
        format: int64
        type: integer
    required:
    - stream
    - intervalSize
    - maxIntervalLag
    - targetSampleSize
    title: RegisterOrdinalValuesPayload
    type: object
host: localhost:8080
info:
  description: An API for stream statistics
  title: Stream Statistics
  version: ""
paths:
  /api/add/{stream}/{ordinal}/{value}:
    get:
      description: add a value to a stream referencing an ordinal position
      operationId: OrdinalValues#add
      parameters:
      - description: The ordinal position of the value
        in: path
        name: ordinal
        required: true
        type: integer
      - description: The stream for which the value is to be added
        in: path
        name: stream
        required: true
        type: string
      - description: The value to be added to the stream
        in: path
        name: value
        required: true
        type: number
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: add
  /api/push:
    post:
      description: Pushes a new ordinal value onto the stream
      operationId: OrdinalValues#push
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PushOrdinalValuesPayload'
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: push
  /api/register:
    post:
      description: Registers a new stream
      operationId: OrdinalValues#register
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RegisterOrdinalValuesPayload'
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: register
produces:
- application/json
schemes:
- http
swagger: "2.0"
